collections:
  - name: ansible.netcommon
    version: 7.1.0
  - name: ansible.utils
    version: 5.1.2
  - name: cisco.ios
    version: 9.0.3
  - name: cisco.iosxr
    version: 10.2.2
  - name: arista.eos
    version: 10.0.1
